<ul>
  <li><a href="tour" {% if basename == 'tour' %} class="current" {% endif %}>tour</a></li>
  <li><a href="itinerary" {% if basename == 'itinerary' %} class="current" {% endif %}>itinerary</a></li>
  <li><a href="about" {% if basename == 'about' %} class="current" {% endif %}>about us</a></li>
  <li><a href="testimonials" {% if basename == 'testimonials' %} class="current" {% endif %}>testimonials</a></li>
  <li><a href="contact" {% if basename == 'contact' %} class="current" {% endif %}>contact</a></li>
  <li><a href="join" {% if basename == 'join' %} class="current" {% endif %}>join</a></li>
  <li><a href="prepare" {% if basename == 'prepare' %} class="current" {% endif %}>prepare</a></li>
</ul>
